### ISSUE TITLE
SCO variable renaming

### ISSUE THREAD

**Issue by Vhati** [icefallgames/SCICompanion#17]
The docs say it is possible to edit SCO entries to manually rename variables.

Unless I'm overlooking something, editing is not currently possible.

[Article](http://scicompanion.com/Documentation/decompiler.html#public-procedure-names-and-variable-names): Documentation - Decompiler

> SCICompanion will try to guess good variable names. For temp and parameter names, you have no control over the the names that are used.
>
> However, for script-wide variables and procedure names, we will place these “guessed” names in the .sco file. **You can edit these names in the SCO pane** to make them more meaningful, and then any script that references that script will pick up those new names when it is decompiled again.

It also doesn't seem possible to disable guessing altogether. This makes bad guesses REALLY annoying. I have to go into disassembly to see what global I'm looking at.

If I want to set my own name, I have to hex edit the sco file. If I try to restore the default "global0" that way, the decompiler will later clobber it if I process a script that makes SCI Companion guess again.

**Comment by icefallgames** [comment]
You can just click on a selected name in the SCO pane (or press F2) to edit it.

**Comment by Vhati** [comment]
Clicking only highlighted for me. Multiple clicks and right-clicks didn't work.

F2 did work.

Is there a way to disable guessing - to either keep default names or prevent clobbering?

**Comment by icefallgames** [comment]
I don't think so. What bad guesses have you noticed?

**Comment by Vhati** [comment]
Quest for Glory 4 (CD) - ScummVM debugger vs Decompiler

global0 = hero (defined in script 28) - Guess is "gGGMaskView_2"
* If I process script 25, the guess is "gTheObj_2".
* If I process script 140: "gGGMaskView_2".

global1 = Glory (defined script 0).
* If I process script 25: "gTheObj".
* If I avoid script 25: gGame (Glory's superclass)

global120 = a time of day variable (values 0-7 for a 24 hr day divided into eight 3 hr spans; set in script 7).
* If I process 626: "gRegister"

Really any guess is distracting for me. I'm reversing the game to patch bugs in assembly for ScummVM. I haven't run into any helpful guesses yet... in the code I've been scrutinizing. Only began recently, and the bad guesses happen to appear frequently.

Being able to individually rename as I go will be helpful. Thanks for the answer.

**Comment by icefallgames** [comment]
It would probably be very easy to offer functionality to disable the guessing, unfortunately I don't have time to work on this anymore. But I'm sure someone on sciprogramming.com would be glad to make a build you a version with a fix.

btw, I believe GfQ4 is an SCI 2.0 game, which isn't officially supported by SCI Companion.

**Comment by Kawa-oneechan** [comment]
Hi, I'm on sciprogramming.com and have a lot of time on my hands.

**Comment by Vhati** [comment]
@Kawa-oneechan:
\*waves\*

I'm not on the forum. Just discovered the alpha build thread. Thanks!

**Comment by Vhati** [comment]
Gah. When I set a non-default name to not get clobbered, temp vars begin to inherit it.

I renamed "global2" to "g2_myCurrentRoom".

Then SCI Companion sees this.

	(= temp6
		(g2_myCurrentRoom exitStyle?)
	)

Guessing decides to rename "temp6" to "g2_myCurrentRoomExitStyle" making it look as if it were a global.

I can stick trailing underscores on all my globals to make those suffixes clearer... Can't do anything to preserve "tempN" indication.

**Comment by icefallgames** [comment]
I think AutoDetectVariableNames is the function that is called that does the guessing. Maybe @Kawa-oneechan can build you a SCI Companion with that call commented out or something.

@Vhati your job will be easier if you join the forums, there is a lot of knowledge there.

**Comment by Kawa-oneechan** [comment]
On it~

**Comment by Vhati** [comment]
@icefallgames Yeah, relevant to the thread (and Kawa) but not to you.
Sorry to be so negative with my first visit.

Your efforts should be commended for producing a tool that functions as well as it does outside of intended use.

> your job will be easier if you join the forums, there is a lot of knowledge there.

This is true.

**Comment by Kawa-oneechan** [comment]
This build of SCI Companion contains _some_ of my own hacks, but is otherwise just like the one you might get from this repository... except it has the one invocation of `AutoDetectVariableNames` commented out! I tested it on a random SCI1-EGA game.

http://helmet.kafuka.org/SCICompanion-noguesses.zip

**Comment by Vhati** [comment]
@Kawa-oneechan:
Good: Looks like that did the trick. All the globalN's survive mass decompilation.

Less good: Manual global rename attempts are rejected. And filename guessing was automatic in that build, until I put a dummy entry in "game.ini" to show it wasn't a blank slate in need of names.

**Comment by Kawa-oneechan** [comment]
If I do put that checkbox in I might as well replace the "Debug Control Flow" checkbox with it :wink:

**Comment by Vhati** [comment]
@Kawa-oneechan:
Um... the class hierarchy is blank?

![chasshierarchy](https://user-images.githubusercontent.com/2262621/48675123-e9e03300-eb22-11e8-919e-0852600b7814.png)

**Comment by Vhati** [comment]
I launched the no-guess build, opened QFG4 (either CD or floppy), and there are no classes.

Started over with a fresh copy of QFG4-CD.
Added a dummy game.ini.

    [Game]
    Language=sci
    [Script]
    n000=n000

Started the no-guess build. Opened the game.
(Hierarchy is populated)
Decompiled all scripts.
(Hierarchy is populated)
Close the game.
Open the game.
(Hierarchy is blank)

**Comment by Kawa-oneechan** [comment]
I launched the no-guess build, opened a fresh QFG4, and the class hierarchy window was populated. `gami.ini` contained only a `Language` setting. Add the one script, reopen the game, class hierarchy still there. Decompile without naming the files, overall rate 96%, hierarchy is still there. Close the application, reopen QFG4, _class hierarchy is blank, and I have no clue._

**Comment by Vhati** [comment]
The hierarchy is blank in the official build too... if I open a game with the dummy game.ini.

If I delete the file and reopen the game in the official build, the hierarchy is populated.
If I delete the file and reopen the game in the no-guess build, the hierarchy is populated.

**Comment by icefallgames** [comment]
Definitely some bugs there, the behavior is erratic. The class hierarchy browser isn't really a supported feature though (I don't believe it's mentioned anywhere in the docs).
I wouldn't put too much effort into guessing what makes it work or doesn't. If you want to debug it, figure out why these aren't being called: SCIClassBrowser::ReloadFromSources and SCIClassBrowser::ReloadFromCompiled.

**Comment by Kawa-oneechan** [comment]
The _laziest_ fix would be to remove the class hierarchy window entirely, considering what Phil said :smile_cat:

**Comment by Vhati** [comment]
@Kawa-oneechan:
Besides room numbers mostly coinciding with unguessed script names, pics, and message pools...
The class browser is my one reliable navigation aid. It provides a tree of *real* names and their file locations.
