### ISSUE TITLE
Repository missing 2 files - fails to compile

### ISSUE THREAD

**Issue by OmerMor** [icefallgames/SCICompanion#3]
There are 2 missing files:

1. `SCICompanionLib\res\bitmapob.bmp` - referenced from `SCICompanionLib\SCICompanionLib.rc`
2. `SCICompanionLib\Src\Resources\AudioResourceSource.cpp` - referenced from `SCICompanionLib\SCICompanionLib.vcxproj`

**Comment by icefallgames** [comment]
Checked in the missing files. That's weird, they were already marked as "included in project", but for some reason didn't get checked in. I had to remove them and add them back.

I've been meaning to try building this on my other machine. Let me know if you run into other issues. You probably will.

**Comment by OmerMor** [comment]
Thanks!
You were too pessimistic - I managed to build successfully. :-)

Closing.

**Comment by icefallgames** [comment]
If you're looking at the code, let me know if you find find anything confusing.

**Comment by OmerMor** [comment]
Sure.
